export enum NETWORK {
  LIVENET = 'livenet',
  TESTNET = 'testnet'
}

export enum CHAIN {
  BEVM = 'bevm',
  BEVM_CANARY = 'bevm_canary',
  B2 = 'bsquared',
  BTC = 'btc',
  SATOSHIVM = 'satoshivm',
  MERLIN = 'merlin',
  ROOTSTOCK = 'rootstock',
  BITLAYER = 'bitlayer',
  BINANCE_CEX = 'binance',
  BINANCE_PAY = 'binance_pay',
  BOB = 'bob',
  ARIBTRUM = 'arbitrum',
  BSC = 'bsc',
  ZKLINK = 'zklinknova',
  ALIENX = 'alienx',
  ZKSYNC = 'zksyncera',
  SCROLL = 'scroll',
  BASE = 'base',
  LINEA = 'linea',
  BLAST = 'blast',
  OP = 'optimism',
  POLYGON = 'polygon_pos',
  TAIKO = 'taiko',
  FANTOM = 'fantom',
  ETHEREUM = 'ethereum',
  XLAYER = 'x_layer',
  ZETACHAIN = 'zetachain',
  MODE = 'mode',
  CORE = 'core',
  FRACTAL = 'fractal',
  MANTA = 'manta',
  ZORA = 'zora',
  OPBNB = 'opbnb',
  SONEIUM = 'soneium',
  STORY = 'story',
  BERA = 'bera',
  PLUME = 'plume',
  GRAVITY = 'gravity',
  CITREA = 'citrea',
  DUCKCHAIN = 'duckchain',
  BITFINITY = 'bitfinity',
  UNICHAIN = 'unichain',
  ZIRCUIT = 'zircuit',
  APECHAIN = 'apechain',
  TELOS = 'telos',
  ABSTRACT = 'abstract',
  MOVEMENT_APTOS = 'movement_aptos',
  APTOS = 'aptos',
  MORPH = 'morph',
  MEZO = 'mezo',
  SWAN = 'swan',
  SUI = 'sui',
  WORLDCHAIN = 'worldchain',
  BOTANIX = 'botanix',
  INK = 'ink',
  HEMI = 'hemi',
  SONIC = 'sonic',
  MEGAETH = 'megaeth',
  CELO = 'celo',
  SOMNIA = 'somnia',
  GOAT = 'goat'
}

export enum CHAIN_TYPE {
  BITCOIN,
  ETHEREUM,
  CEX,
  MOVEMENT_APTOS,
  APTOS,
  SUI
}
